apiVersion: v1
kind: Service
metadata:
  name: reinvocation
  labels:
    scenario: reinvocation
spec:
  type: ClusterIP
  selector:
    scenario: reinvocation
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
