apiVersion: batch/v1
kind: Job
metadata:
  name: label-overwrite-webhook-cert-setup
  labels:
    scenario: label-overwrite
spec:
  template:
    spec:
      serviceAccountName: webhook-cert-sa
      initContainers:
      - name: webhook-cert-setup
        image: cribl/k8s-webhook-cert-manager:1.0.1
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "label-overwrite"
          - "--webhook"
          - "label-overwrite.marcusnoble.com"
          - "--secret"
          - "label-overwrite-secret"
          - "--namespace"
          - "default"
      containers:
      - name: set-failure-policy
        image: quay.io/giantswarm/kubectl:1.27.4
        command:
        - sh
        - -c
        - |
          kubectl patch mutatingwebhookconfiguration label-overwrite.marcusnoble.com \
            --type='json' -p "[{'op': 'add', 'path': '/webhooks/0/failurePolicy', 'value':'Fail'}]"
      restartPolicy: OnFailure
  backoffLimit: 3
