apiVersion: v1
kind: Service
metadata:
  name: label-overwrite
  labels:
    scenario: label-overwrite
spec:
  type: ClusterIP
  selector:
    scenario: label-overwrite
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
