apiVersion: v1
kind: Service
metadata:
  name: fork-bomb
  labels:
    scenario: fork-bomb
spec:
  type: ClusterIP
  selector:
    scenario: fork-bomb
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
