apiVersion: v1
kind: Service
metadata:
  name: cut-off-response
  labels:
    scenario: cut-off-response
spec:
  type: ClusterIP
  selector:
    scenario: cut-off-response
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
