apiVersion: v1
kind: Service
metadata:
  name: redirect
  labels:
    scenario: redirect
spec:
  type: ClusterIP
  selector:
    scenario: redirect
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
